CREATE TABLE SortimentSkupina
(
	id 		INT UNSIGNED	PRIMARY KEY AUTO_INCREMENT,
	nazev	VARCHAR(30)		NOT NULL,
	label1	VARCHAR(15),
	label2	VARCHAR(15),
	label3	VARCHAR(15),
	label4	VARCHAR(15),
	label5	VARCHAR(15)
);